name: CI-CD Staging (Test Branch) Deployment Pipeline

on:
  push:
    # Staging is our test branch. All test deployments run from this branch only.
    branches: [ "staging" ]  

jobs:
  deploy:
    runs-on: self-hosted  # Targets Lightsail server
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Models Folder
        uses: actions/cache@v3
        with:
          path: models/
          key: ${{ runner.os }}-models-${{ hashFiles('models/**') }}  # Caches based on the contents of the models folder
          restore-keys: |
            ${{ runner.os }}-models-

      - name: Deploy Staging with Docker Compose
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          docker compose -p intelligrader-staging -f docker-compose.staging.yml up -d --build --remove-orphans
          
          docker image prune -f

      - name: Health Check (Staging)
        run: |
          chmod +x scripts/health-check-staging.sh
          scripts/health-check-staging.sh

      - name: Status Check
        run: docker ps
