name: CI-CD Deployment Pipeline

on:
  push:
    branches: [ "main" ]  

jobs:
  deploy:
    runs-on: self-hosted  # Targets Lightsail server
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Deploy with Docker Compose
        run: |
          docker compose down --remove-orphans
          
          docker compose up -d --build
          
          docker image prune -f

      - name: Trigger Model Sync On Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker exec intelligrader-api python -m model_manager

      - name: Status Check
        run: docker ps